services:
  - type: web
    name: lecfac-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    envVars:
      - key: DATABASE_TYPE
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: lecfac-db
          property: connectionString
      - key: GCP_PROJECT_ID
        sync: false
      - key: DOC_AI_LOCATION
        sync: false
      - key: DOC_AI_PROCESSOR_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: lecfac-db
    plan: free
    databaseName: lecfac
    user: lecfac_user

