services:
  - type: web
    name: lecfac-api
    env: docker
    autoDeploy: true
    healthCheckPath: /verify-tesseract
    envVars:
      - key: DATABASE_TYPE
        value: postgresql
      - key: DATABASE_URL
        sync: false
      - key: GCP_PROJECT_ID
        sync: false
      - key: DOC_AI_LOCATION
        sync: false
      - key: DOC_AI_PROCESSOR_ID
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false



databases:
  - name: lecfac-db
    plan: free
    databaseName: lecfac
    user: lecfac_user






